// Tokens that, when referenced by a tool description or requested as a param,
// are out of place for most tools and signal secret/credential access.
export const SENSITIVE_TOKENS: string[] = [
	"id_rsa",
	"id_ed25519",
	".ssh",
	"ssh_key",
	"ssh key",
	"private key",
	"privatekey",
	".env",
	"dotenv",
	"env var",
	"environment variable",
	"aws_secret",
	"aws_access_key",
	".aws/credentials",
	"credentials",
	"password",
	"passwd",
	"secret",
	"api_key",
	"apikey",
	"access_token",
	"auth token",
	"authorization",
	"bearer",
	"cookie",
	"session token",
	"keychain",
	"/etc/passwd",
	".npmrc",
	".git-credentials",
];

// Parameter names that are dangerous on tools claiming to be read-only/informational.
export const DANGEROUS_PARAM_NAMES: string[] = [
	"command",
	"cmd",
	"code",
	"script",
	"shell",
	"exec",
	"eval",
	"file_contents",
	"file_content",
	"env",
	"environment",
	"conversation_history",
	"history",
	"context",
	"ssh_key",
	"private_key",
	"credentials",
];
