// Generates src/generated/version.ts: scanner version (from package.json, bumped
// by semantic-release) + a checks hash derived from the detection sources. The
// hash changes only when detection logic changes, so it drives staleness without
// any manual bumping.
import { createHash } from 'node:crypto'
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')

// Any change to these files should invalidate prior scan results.
const DETECTION_FILES = [
  'src/rules/heuristics.ts',
  'src/rules/sinks.ts',
  'src/rules/sensitive.ts',
  'src/rules/popular.ts',
  'src/scanners/metadata.ts',
  'src/scanners/static.ts',
  'src/scoring.ts',
].sort()

const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'))
const hash = createHash('sha256')
for (const rel of DETECTION_FILES) hash.update(`${rel}\n${readFileSync(join(root, rel), 'utf8')}`)
const checks = hash.digest('hex').slice(0, 12)

const outDir = join(root, 'src/generated')
mkdirSync(outDir, { recursive: true })
writeFileSync(
  join(outDir, 'version.ts'),
  `// AUTO-GENERATED by scripts/gen-version.mjs — do not edit.\n` +
    `export const SCANNER_VERSION = '${pkg.version}'\n` +
    `export const CHECKS_VERSION = '${checks}'\n`,
)
process.stderr.write(`gen-version: v${pkg.version} checks ${checks}\n`)
