#!/usr/bin/env node
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { type CatalogRow, isOutdated } from "./catalog.js";
import {
	controlsForFinding,
	evaluateFrameworks,
	FRAMEWORKS,
} from "./frameworks.js";
import type { Finding, ScanReport } from "./model.js";
import { CHECKS_VERSION, SCANNER_VERSION } from "./version.js";

const CURRENT_CHECKS = String(CHECKS_VERSION);

const SUMMARY = "data/summary.json";
const RESULTS_DIR = "data/results";
const OUT = "site";

const BAND_COLOR: Record<string, string> = {
	verified: "#2da44e",
	ok: "#3fb950",
	warn: "#d29922",
	danger: "#cf222e",
	unknown: "#8b949e",
};

function esc(s: string | undefined): string {
	return (s ?? "")
		.replace(/&/g, "&amp;")
		.replace(/</g, "&lt;")
		.replace(/>/g, "&gt;")
		.replace(/"/g, "&quot;");
}

function scoreText(row: CatalogRow): string {
	return row.score === null ? "n/a" : String(row.score);
}

const PAGE_CSS = `
:root{color-scheme:light dark}
*{box-sizing:border-box}
body{margin:0;font:15px/1.5 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;
  background:#0d1117;color:#e6edf3}
a{color:#58a6ff;text-decoration:none}a:hover{text-decoration:underline}
.wrap{max-width:1100px;margin:0 auto;padding:32px 20px}
h1{font-size:28px;margin:0 0 4px}
.sub{color:#8b949e;margin:0 0 24px}
input{background:#161b22;border:1px solid #30363d;color:#e6edf3;border-radius:6px;
  padding:8px 12px;width:100%;max-width:340px;margin-bottom:16px;font-size:14px}
table{width:100%;border-collapse:collapse;font-size:14px}
th,td{text-align:left;padding:10px 12px;border-bottom:1px solid #21262d}
th{color:#8b949e;font-weight:600;cursor:pointer;user-select:none;white-space:nowrap}
th:hover{color:#e6edf3}
tbody tr:hover{background:#161b22}
.score{display:inline-block;min-width:34px;text-align:center;border-radius:6px;
  padding:2px 8px;font-weight:700;color:#fff}
.pill{display:inline-block;border-radius:10px;padding:1px 8px;font-size:12px;margin-right:4px}
.desc{color:#8b949e;max-width:420px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.finding{border:1px solid #30363d;border-radius:8px;padding:12px 14px;margin:10px 0;background:#161b22}
.finding .sev{font-weight:700;text-transform:uppercase;font-size:12px;margin-right:8px}
.finding code{background:#0d1117;padding:2px 6px;border-radius:4px;font-size:12px;color:#e6edf3}
.snippet{color:#8b949e;font-family:ui-monospace,monospace;font-size:12px;margin-top:6px;word-break:break-all}
.back{color:#8b949e}
.outdated{display:inline-block;border-radius:10px;padding:1px 8px;font-size:12px;
  background:#3d2c00;color:#d29922;white-space:nowrap}
.banner{background:#3d2c00;color:#d29922;border:1px solid #5c4200;border-radius:8px;
  padding:10px 14px;margin:0 0 20px;font-size:14px}
.callout{background:#3d2c00;color:#d29922;border:1px solid #5c4200;border-radius:8px;
  padding:12px 14px;margin:12px 0}
.fw{display:inline-block;border-radius:10px;padding:1px 8px;font-size:12px;margin-right:4px;
  background:#161b22;border:1px solid #30363d;color:#8b949e;white-space:nowrap}
.fw.bad{border-color:#5c2326;color:#f85149}
.fw.good{border-color:#238636;color:#3fb950}
.off.official{border-color:#238636;color:#3fb950}
.off.unofficial{border-color:#30363d;color:#8b949e}
.off.unknown{border-color:#30363d;color:#6e7681}
.chip{display:inline-block;border-radius:10px;padding:0 6px;font-size:11px;margin-left:4px;
  background:#0d1117;border:1px solid #30363d;color:#8b949e}
.ctrl{display:flex;gap:8px;padding:6px 0;border-bottom:1px solid #21262d;font-size:14px}
.ctrl .st{min-width:80px;font-weight:600}
.ctrl .st.pass{color:#3fb950}.ctrl .st.fail{color:#f85149}.ctrl .st.na{color:#8b949e}
footer{color:#8b949e;margin-top:40px;font-size:13px}
.pager{display:flex;gap:12px;align-items:center;margin-top:16px}
.pager button{background:#161b22;border:1px solid #30363d;color:#e6edf3;border-radius:6px;
  padding:6px 12px;font-size:14px;cursor:pointer}
.pager button:disabled{opacity:.4;cursor:default}
.pager #pageinfo{color:#8b949e;font-size:13px}
`;

function layout(title: string, body: string): string {
	return `<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>${esc(title)}</title><style>${PAGE_CSS}</style></head>
<body><div class="wrap">${body}
<footer>Generated by <a href="https://github.com/nirberko/mcpscan">mcpscan</a> · scores reflect automated static + metadata analysis, not a guarantee.</footer>
</div></body></html>`;
}

function scoreSpan(row: CatalogRow): string {
	return `<span class="score" style="background:${BAND_COLOR[row.band]}">${scoreText(row)}</span>`;
}

// Short per-framework pill: "MCP 5/6" = passed/assessed controls. Red when any
// control fails, green when all assessed pass, gray when nothing assessed.
function frameworkPills(row: CatalogRow): string {
	return FRAMEWORKS.map((fw) => {
		const c = row.frameworks?.[fw.id];
		if (!c) return "";
		const assessed = c.passed + c.failed;
		const short = fw.name.replace(/^OWASP /, "").replace(/ Top 10$/, "");
		const cls = c.failed ? "bad" : assessed ? "good" : "";
		return `<span class="fw ${cls}" title="${esc(fw.name)} ${fw.version}: ${c.passed}/${assessed} assessed controls pass, ${c.notAssessed} not assessed">${esc(short)} ${c.passed}/${assessed}</span>`;
	}).join("");
}

// Publisher label: green "official" (vendor-published), gray "unofficial"
// (community), faint "unknown". Reuses the .fw pill box via a shared class.
function officialityPill(row: CatalogRow): string {
	return `<span class="fw off ${row.officiality}">${row.officiality}</span>`;
}

const PAGE_SIZE = 100;

// Compact per-row payload for the client. Text fields are pre-escaped; `fp` is
// already HTML. `q` is a lowercased plaintext key for filtering. Short keys keep
// catalog.json small across ~13k rows.
function rowData(r: CatalogRow) {
	const findings = Object.entries(r.counts)
		.map(([s, n]) => `${n} ${s}`)
		.join(", ");
	return {
		sc: r.score,
		co: BAND_COLOR[r.band],
		id: esc(r.id),
		sl: r.slug,
		of: r.officiality,
		d: esc(r.description),
		fi: esc(findings || "—"),
		ff: Object.values(r.frameworks ?? {}).reduce((n, c) => n + c.failed, 0),
		fp: frameworkPills(r) || "—",
		so: esc(Object.keys(r.sources).join(", ")),
		sv: esc(r.scannerVersion),
		od: isOutdated(r, CURRENT_CHECKS),
		q: `${r.id} ${r.description ?? ""}`.toLowerCase(),
	};
}

function catalogJson(rows: CatalogRow[]): string {
	return JSON.stringify(rows.map(rowData));
}

function indexPage(rows: CatalogRow[]): string {
	const scored = rows.filter((r) => r.score !== null).length;
	const stats = {
		total: rows.length,
		danger: rows.filter((r) => r.band === "danger").length,
		warn: rows.filter((r) => r.band === "warn").length,
		outdated: rows.filter((r) => isOutdated(r, CURRENT_CHECKS)).length,
	};

	const banner = stats.outdated
		? `<div class="banner">⚠ ${stats.outdated} of ${scored} scored results predate the current detection (mcpscan v${SCANNER_VERSION}) and are queued for re-scan.</div>`
		: "";

	const body = `<h1>MCP Security Catalog</h1>
<p class="sub">${stats.total} servers · ${stats.danger} danger · ${stats.warn} warn · scanner v${SCANNER_VERSION}.
Continuously scanned from the <a href="https://registry.modelcontextprotocol.io">official MCP registry</a>.</p>
${banner}
<input id="q" placeholder="Filter by name or description…">
<table id="t"><thead><tr>
<th data-col="sc" data-num="1">Score</th><th data-col="id">Server</th>
<th data-col="of">Publisher</th><th data-col="d">Description</th><th data-col="fi">Findings</th>
<th data-col="ff" data-num="1">Frameworks</th><th data-col="so">Source</th>
<th data-col="od" data-num="1">Scanned</th>
</tr></thead><tbody></tbody></table>
<div class="pager"><button id="prev">← prev</button><span id="pageinfo"></span><button id="next">next →</button></div>
<p class="sub" id="empty" style="display:none">No matching servers.</p>
<script>
const SIZE=${PAGE_SIZE};
let DATA=[],view=[],page=0,sortCol='sc',dir=1;
const tb=document.querySelector('#t tbody'),q=document.getElementById('q'),
  info=document.getElementById('pageinfo'),empty=document.getElementById('empty');
function row(r){const s=r.sc==null?'n/a':r.sc;
  const scan=r.od?'<span class="outdated">v'+r.sv+' · outdated</span>':'<span class="sub">v'+r.sv+'</span>';
  return '<tr><td><span class="score" style="background:'+r.co+'">'+s+'</span></td>'
    +'<td><a href="server/'+r.sl+'.html">'+r.id+'</a></td>'
    +'<td><span class="fw off '+r.of+'">'+r.of+'</span></td>'
    +'<td class="desc" title="'+r.d+'">'+r.d+'</td>'
    +'<td>'+r.fi+'</td><td>'+r.fp+'</td><td>'+r.so+'</td><td>'+scan+'</td></tr>';}
function apply(){const v=q.value.toLowerCase();
  view=v?DATA.filter(r=>r.q.includes(v)):DATA.slice();
  const num=sortCol==='sc'||sortCol==='ff'||sortCol==='od';
  view.sort((a,b)=>{let x=a[sortCol],y=b[sortCol];
    if(sortCol==='sc'){x=x==null?101:x;y=y==null?101:y}
    if(sortCol==='od'){x=x?0:1;y=y?0:1}
    if(!num){x=String(x);y=String(y)}
    return (x>y?1:x<y?-1:0)*dir;});
  page=0;render();}
function render(){const pages=Math.max(1,Math.ceil(view.length/SIZE));
  page=Math.min(page,pages-1);
  const slice=view.slice(page*SIZE,page*SIZE+SIZE);
  tb.innerHTML=slice.map(row).join('');
  empty.style.display=view.length?'none':'';
  info.textContent=view.length?('page '+(page+1)+' / '+pages+' · '+view.length+' servers'):'';
  document.getElementById('prev').disabled=page<=0;
  document.getElementById('next').disabled=page>=pages-1;}
q.oninput=apply;
document.getElementById('prev').onclick=()=>{page--;render()};
document.getElementById('next').onclick=()=>{page++;render()};
document.querySelector('#t thead').addEventListener('click',e=>{const th=e.target.closest('th');if(!th)return;
  const c=th.dataset.col;dir=c===sortCol?-dir:1;sortCol=c;apply();});
fetch('catalog.json').then(r=>r.json()).then(d=>{DATA=d;apply();});
</script>`;
	return layout("MCP Security Catalog", body);
}

function findingHtml(f: Finding): string {
	const color = {
		critical: "#cf222e",
		high: "#cf222e",
		medium: "#d29922",
		low: "#58a6ff",
		info: "#8b949e",
	}[f.severity];
	return `<div class="finding">
<span class="sev" style="color:${color}">${f.severity}</span>
<strong>${esc(f.title)}</strong> <code>${esc(f.id)}</code>${controlsForFinding(f)
		.map((c) => `<span class="chip">${esc(c.code)}</span>`)
		.join("")}
<div>${esc(f.detail)}</div>
<div class="snippet">↳ ${esc(f.evidence.source)}${f.evidence.line ? `:${f.evidence.line}` : ""} — ${esc(f.evidence.snippet)}</div>
</div>`;
}

// Per-framework compliance checklist. Failed controls name their findings;
// controls the scanner has no checks for read "not assessed", never "pass".
function frameworksHtml(report: ScanReport): string {
	return evaluateFrameworks(report.findings)
		.map((r) => {
			const rows = r.controls
				.map((c) => {
					const st =
						c.status === "fail"
							? '<span class="st fail">✗ fail</span>'
							: c.status === "pass"
								? '<span class="st pass">✓ pass</span>'
								: '<span class="st na">– n/a</span>';
					const why = c.failing.length
						? `<span class="sub"> — ${esc(c.failing.map((f) => f.title).join("; "))}</span>`
						: "";
					return `<div class="ctrl">${st}<span><code>${esc(c.code)}</code> ${esc(c.name)}${why}</span></div>`;
				})
				.join("\n");
			const title = r.framework.url
				? `<a href="${esc(r.framework.url)}">${esc(r.framework.name)} (${esc(r.framework.version)})</a>`
				: `${esc(r.framework.name)} (${esc(r.framework.version)})`;
			return `<h2>${title} <span class="sub">${r.passed}/${r.passed + r.failed} assessed controls pass · ${r.notAssessed} not assessed</span></h2>\n${rows}`;
		})
		.join("\n");
}

function detailPage(row: CatalogRow, report: ScanReport): string {
	const layers = [
		report.layers.metadata && "metadata",
		report.layers.static && "static",
	]
		.filter(Boolean)
		.join(" + ");
	const findings = report.findings.length
		? [...report.findings]
				.sort((a, b) => severityRank(b.severity) - severityRank(a.severity))
				.map(findingHtml)
				.join("\n")
		: '<p class="sub">No findings.</p>';
	const errors = report.errors.length
		? `<p class="sub">Scan notes: ${esc(report.errors.map((e) => e.message).join("; "))}</p>`
		: "";
	const callout = isOutdated(row, CURRENT_CHECKS)
		? `<div class="callout">⚠ Scored with mcpscan v${esc(row.scannerVersion)}; detection has changed since (checks ${esc(row.checksVersion)} → ${CURRENT_CHECKS}). This result may miss newer detections and is queued for re-scan.</div>`
		: "";
	const body = `<p><a class="back" href="../index.html">← catalog</a></p>
<h1>${scoreSpan(row)} &nbsp;${esc(row.id)} &nbsp;${officialityPill(row)}</h1>
<p class="sub">${esc(row.description)}</p>
<p class="sub">target <code>${esc(row.scanTarget)}</code> · scanned ${layers || "nothing"} · ${esc(row.scannedAt)}<br>
mcpscan v${esc(row.scannerVersion)} · checks ${esc(row.checksVersion)}</p>
${callout}
${errors}
${findings}
${frameworksHtml(report)}`;
	return layout(`${row.id} — mcpscan`, body);
}

function severityRank(s: string): number {
	return ["info", "low", "medium", "high", "critical"].indexOf(s);
}

// Machine-readable registry for programmatic consumers. Stable shape, no HTML.
function registryJson(rows: CatalogRow[]): string {
	const servers = rows.map((r) => ({
		id: r.id,
		slug: r.slug,
		title: r.title,
		description: r.description,
		version: r.version,
		scanTarget: r.scanTarget,
		sources: r.sources,
		score: r.score,
		band: r.band,
		officiality: r.officiality,
		findingCounts: r.counts,
		frameworks: r.frameworks ?? {},
		scannedAt: r.scannedAt,
		scannerVersion: r.scannerVersion,
		checksVersion: r.checksVersion,
		outdated: isOutdated(r, CURRENT_CHECKS),
		report: `server/${r.slug}.html`,
		badge: `badge/${r.slug}.svg`,
	}));
	return JSON.stringify(
		{
			generatedAt: new Date().toISOString(),
			scannerVersion: SCANNER_VERSION,
			checksVersion: CURRENT_CHECKS,
			count: servers.length,
			servers,
		},
		null,
		2,
	);
}

function badgeSvg(row: CatalogRow): string {
	const label = "mcpscan";
	const value = scoreText(row);
	const color = BAND_COLOR[row.band];
	const lw = 58;
	const vw = 34;
	const w = lw + vw;
	return `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="20" role="img" aria-label="${label}: ${value}">
<linearGradient id="s" x2="0" y2="100%"><stop offset="0" stop-color="#bbb" stop-opacity=".1"/><stop offset="1" stop-opacity=".1"/></linearGradient>
<rect width="${w}" height="20" rx="3" fill="#555"/>
<rect x="${lw}" width="${vw}" height="20" rx="3" fill="${color}"/>
<rect width="${w}" height="20" rx="3" fill="url(#s)"/>
<g fill="#fff" text-anchor="middle" font-family="Verdana,sans-serif" font-size="11">
<text x="${lw / 2}" y="14">${label}</text>
<text x="${lw + vw / 2}" y="14">${value}</text>
</g></svg>`;
}

async function main(): Promise<void> {
	const rows = JSON.parse(await readFile(SUMMARY, "utf8")) as CatalogRow[];
	await mkdir(join(OUT, "server"), { recursive: true });
	await mkdir(join(OUT, "badge"), { recursive: true });

	await writeFile(join(OUT, "index.html"), indexPage(rows));
	await writeFile(join(OUT, "catalog.json"), catalogJson(rows));
	await writeFile(join(OUT, "registry.json"), registryJson(rows));

	for (const row of rows) {
		let report: ScanReport;
		try {
			report = JSON.parse(
				await readFile(join(RESULTS_DIR, `${row.slug}.json`), "utf8"),
			) as ScanReport;
		} catch (e) {
			process.stderr.write(
				`build-site: skipping ${row.slug}: ${(e as Error).message}\n`,
			);
			continue;
		}
		await writeFile(
			join(OUT, "server", `${row.slug}.html`),
			detailPage(row, report),
		);
		await writeFile(join(OUT, "badge", `${row.slug}.svg`), badgeSvg(row));
	}

	process.stderr.write(`Built site for ${rows.length} servers → ${OUT}/\n`);
}

main().catch((e) => {
	process.stderr.write(`build-site: ${(e as Error).message}\n`);
	process.exit(1);
});
