#!/usr/bin/env node
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { isOutdated, type CatalogRow } from './catalog.js'
import { CHECKS_VERSION } from './version.js'
import type { Finding, ScanReport } from './model.js'

const CURRENT_CHECKS = String(CHECKS_VERSION)

const SUMMARY = 'data/summary.json'
const RESULTS_DIR = 'data/results'
const OUT = 'site'

const BAND_COLOR: Record<string, string> = {
  verified: '#2da44e',
  ok: '#3fb950',
  warn: '#d29922',
  danger: '#cf222e',
  unknown: '#8b949e',
}

function esc(s: string | undefined): string {
  return (s ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

function scoreText(row: CatalogRow): string {
  return row.score === null ? 'n/a' : String(row.score)
}

const PAGE_CSS = `
:root{color-scheme:light dark}
*{box-sizing:border-box}
body{margin:0;font:15px/1.5 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;
  background:#0d1117;color:#e6edf3}
a{color:#58a6ff;text-decoration:none}a:hover{text-decoration:underline}
.wrap{max-width:1100px;margin:0 auto;padding:32px 20px}
h1{font-size:28px;margin:0 0 4px}
.sub{color:#8b949e;margin:0 0 24px}
input{background:#161b22;border:1px solid #30363d;color:#e6edf3;border-radius:6px;
  padding:8px 12px;width:100%;max-width:340px;margin-bottom:16px;font-size:14px}
table{width:100%;border-collapse:collapse;font-size:14px}
th,td{text-align:left;padding:10px 12px;border-bottom:1px solid #21262d}
th{color:#8b949e;font-weight:600;cursor:pointer;user-select:none;white-space:nowrap}
th:hover{color:#e6edf3}
tbody tr:hover{background:#161b22}
.score{display:inline-block;min-width:34px;text-align:center;border-radius:6px;
  padding:2px 8px;font-weight:700;color:#fff}
.pill{display:inline-block;border-radius:10px;padding:1px 8px;font-size:12px;margin-right:4px}
.desc{color:#8b949e;max-width:420px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.finding{border:1px solid #30363d;border-radius:8px;padding:12px 14px;margin:10px 0;background:#161b22}
.finding .sev{font-weight:700;text-transform:uppercase;font-size:12px;margin-right:8px}
.finding code{background:#0d1117;padding:2px 6px;border-radius:4px;font-size:12px;color:#e6edf3}
.snippet{color:#8b949e;font-family:ui-monospace,monospace;font-size:12px;margin-top:6px;word-break:break-all}
.back{color:#8b949e}
.outdated{display:inline-block;border-radius:10px;padding:1px 8px;font-size:12px;
  background:#3d2c00;color:#d29922;white-space:nowrap}
.banner{background:#3d2c00;color:#d29922;border:1px solid #5c4200;border-radius:8px;
  padding:10px 14px;margin:0 0 20px;font-size:14px}
.callout{background:#3d2c00;color:#d29922;border:1px solid #5c4200;border-radius:8px;
  padding:12px 14px;margin:12px 0}
footer{color:#8b949e;margin-top:40px;font-size:13px}
`

function layout(title: string, body: string): string {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>${esc(title)}</title><style>${PAGE_CSS}</style></head>
<body><div class="wrap">${body}
<footer>Generated by <a href="https://github.com/nirberko/mcpscan">mcpscan</a> · scores reflect automated static + metadata analysis, not a guarantee.</footer>
</div></body></html>`
}

function scoreSpan(row: CatalogRow): string {
  return `<span class="score" style="background:${BAND_COLOR[row.band]}">${scoreText(row)}</span>`
}

function indexPage(rows: CatalogRow[]): string {
  const scored = rows.filter((r) => r.score !== null).length
  const stats = {
    total: rows.length,
    danger: rows.filter((r) => r.band === 'danger').length,
    warn: rows.filter((r) => r.band === 'warn').length,
    outdated: rows.filter((r) => isOutdated(r, CURRENT_CHECKS)).length,
  }
  const trs = rows
    .map((r) => {
      const findings = Object.entries(r.counts)
        .map(([s, n]) => `${n} ${s}`)
        .join(', ')
      const stale = isOutdated(r, CURRENT_CHECKS)
      const staleCell = stale
        ? `<span class="outdated">v${esc(r.checksVersion)} · outdated</span>`
        : `<span class="sub">v${esc(r.checksVersion)}</span>`
      return `<tr>
<td data-sort="${r.score ?? 101}">${scoreSpan(r)}</td>
<td><a href="server/${r.slug}.html">${esc(r.id)}</a></td>
<td class="desc" title="${esc(r.description)}">${esc(r.description)}</td>
<td>${esc(findings || '—')}</td>
<td>${esc(Object.keys(r.sources).join(', '))}</td>
<td data-sort="${stale ? 0 : 1}">${staleCell}</td>
</tr>`
    })
    .join('\n')

  const banner = stats.outdated
    ? `<div class="banner">⚠ ${stats.outdated} of ${scored} scored results predate the current checks (v${CURRENT_CHECKS}) and are queued for re-scan.</div>`
    : ''

  const body = `<h1>MCP Security Catalog</h1>
<p class="sub">${stats.total} servers · ${stats.danger} danger · ${stats.warn} warn · checks v${CURRENT_CHECKS}.
Continuously scanned from the <a href="https://registry.modelcontextprotocol.io">official MCP registry</a>.</p>
${banner}
<input id="q" placeholder="Filter by name or description…">
<table id="t"><thead><tr>
<th data-col="0" data-num="1">Score</th><th data-col="1">Server</th>
<th data-col="2">Description</th><th data-col="3">Findings</th><th data-col="4">Source</th>
<th data-col="5" data-num="1">Checks</th>
</tr></thead><tbody>${trs}</tbody></table>
<script>
const t=document.getElementById('t'),q=document.getElementById('q');
q.oninput=()=>{const v=q.value.toLowerCase();
for(const tr of t.tBodies[0].rows){tr.style.display=tr.cells[1].textContent.toLowerCase().includes(v)||tr.cells[2].textContent.toLowerCase().includes(v)?'':'none'}};
let dir=1;
t.tHead.addEventListener('click',e=>{const th=e.target.closest('th');if(!th)return;
const c=+th.dataset.col,num=th.dataset.num;dir=-dir;
const rows=[...t.tBodies[0].rows];
rows.sort((a,b)=>{const x=num?+a.cells[c].dataset.sort:a.cells[c].textContent,
y=num?+b.cells[c].dataset.sort:b.cells[c].textContent;return (x>y?1:x<y?-1:0)*dir});
for(const r of rows)t.tBodies[0].appendChild(r)});
</script>`
  return layout('MCP Security Catalog', body)
}

function findingHtml(f: Finding): string {
  const color = { critical: '#cf222e', high: '#cf222e', medium: '#d29922', low: '#58a6ff', info: '#8b949e' }[
    f.severity
  ]
  return `<div class="finding">
<span class="sev" style="color:${color}">${f.severity}</span>
<strong>${esc(f.title)}</strong> <code>${esc(f.id)}</code>
<div>${esc(f.detail)}</div>
<div class="snippet">↳ ${esc(f.evidence.source)}${f.evidence.line ? `:${f.evidence.line}` : ''} — ${esc(f.evidence.snippet)}</div>
</div>`
}

function detailPage(row: CatalogRow, report: ScanReport): string {
  const layers = [report.layers.metadata && 'metadata', report.layers.static && 'static']
    .filter(Boolean)
    .join(' + ')
  const findings = report.findings.length
    ? [...report.findings]
        .sort((a, b) => severityRank(b.severity) - severityRank(a.severity))
        .map(findingHtml)
        .join('\n')
    : '<p class="sub">No findings.</p>'
  const errors = report.errors.length
    ? `<p class="sub">Scan notes: ${esc(report.errors.map((e) => e.message).join('; '))}</p>`
    : ''
  const callout = isOutdated(row, CURRENT_CHECKS)
    ? `<div class="callout">⚠ Scored with checks v${esc(row.checksVersion)}; current is v${CURRENT_CHECKS}. This result may miss newer detections and is queued for re-scan.</div>`
    : ''
  const body = `<p><a class="back" href="../index.html">← catalog</a></p>
<h1>${scoreSpan(row)} &nbsp;${esc(row.id)}</h1>
<p class="sub">${esc(row.description)}</p>
<p class="sub">target <code>${esc(row.scanTarget)}</code> · scanned ${layers || 'nothing'} · ${esc(row.scannedAt)}<br>
mcpscan v${esc(row.scannerVersion)} · checks v${esc(row.checksVersion)}</p>
${callout}
${errors}
${findings}`
  return layout(`${row.id} — mcpscan`, body)
}

function severityRank(s: string): number {
  return ['info', 'low', 'medium', 'high', 'critical'].indexOf(s)
}

function badgeSvg(row: CatalogRow): string {
  const label = 'mcpscan'
  const value = scoreText(row)
  const color = BAND_COLOR[row.band]
  const lw = 58
  const vw = 34
  const w = lw + vw
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="20" role="img" aria-label="${label}: ${value}">
<linearGradient id="s" x2="0" y2="100%"><stop offset="0" stop-color="#bbb" stop-opacity=".1"/><stop offset="1" stop-opacity=".1"/></linearGradient>
<rect width="${w}" height="20" rx="3" fill="#555"/>
<rect x="${lw}" width="${vw}" height="20" rx="3" fill="${color}"/>
<rect width="${w}" height="20" rx="3" fill="url(#s)"/>
<g fill="#fff" text-anchor="middle" font-family="Verdana,sans-serif" font-size="11">
<text x="${lw / 2}" y="14">${label}</text>
<text x="${lw + vw / 2}" y="14">${value}</text>
</g></svg>`
}

async function main(): Promise<void> {
  const rows = JSON.parse(await readFile(SUMMARY, 'utf8')) as CatalogRow[]
  await mkdir(join(OUT, 'server'), { recursive: true })
  await mkdir(join(OUT, 'badge'), { recursive: true })

  await writeFile(join(OUT, 'index.html'), indexPage(rows))

  for (const row of rows) {
    const report = JSON.parse(
      await readFile(join(RESULTS_DIR, `${row.slug}.json`), 'utf8'),
    ) as ScanReport
    await writeFile(join(OUT, 'server', `${row.slug}.html`), detailPage(row, report))
    await writeFile(join(OUT, 'badge', `${row.slug}.svg`), badgeSvg(row))
  }

  process.stderr.write(`Built site for ${rows.length} servers → ${OUT}/\n`)
}

main().catch((e) => {
  process.stderr.write(`build-site: ${(e as Error).message}\n`)
  process.exit(1)
})
