// SCANNER_VERSION (from package.json / releases) and CHECKS_VERSION (hash of the
// detection sources) are generated by scripts/gen-version.mjs on prebuild/pretest.
export { SCANNER_VERSION, CHECKS_VERSION } from './generated/version.js'
